apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: ""
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  writeOutputsToSecret:
    name: helloworld-outputs
